# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm install hardhat
            npm install @nomiclabs/hardhat-ethers ethers
            npm install @openzeppelin/contracts
            npm install chai
            npm install @nomiclabs/hardhat-truffle5
            npm install "@nomiclabs/hardhat-web3@^2.0.0"
      - run:
          name: test contracts
          command: |
            npx hardhat test
workflows:
  main:
    jobs:
      - build-and-test
