/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AuthInterface extends ethers.utils.Interface {
  functions: {
    "isAdministrator(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isAdministrator",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isAdministrator",
    data: BytesLike
  ): Result;

  events: {};
}

export class Auth extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AuthInterface;

  functions: {
    isAdministrator(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isAdministrator(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isAdministrator(user: string, overrides?: CallOverrides): Promise<boolean>;

  "isAdministrator(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isAdministrator(user: string, overrides?: CallOverrides): Promise<boolean>;

    "isAdministrator(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isAdministrator(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isAdministrator(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isAdministrator(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAdministrator(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
